# Fly.io deployment configuration for RapidReach
app = 'rapidreach-test'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = '15s'
    interval = '60s'
    method = 'GET'
    timeout = '10s'
    path = '/'

[vm]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 1024

[[statics]]
  guest_path = '/app/dist'
  url_prefix = '/'
