// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vohjarhfvaphzwjzjcnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvaGphcmhmdmFwaHp3anpqY256Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzQ2NzksImV4cCI6MjA2NzkxMDY3OX0.fTMJcBvsRKH_hge7Q1zvh8GSRLt-egCG6W9Mz6JavMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});